### ISSUE TITLE
PNPM Migration

### ISSUE THREAD

**Issue by cokia** [sparcs-kaist/taxi-sample-generator#28]
# Summary 

기존 패키지 매니저인 `npm`을 `pnpm`으로 대체합니다.

# Tasks 

- [x] NPM 의존성 제거
- [x] PNPM 셋업
- [x] gitignore에 package-lock.json 파일 추가
- [x] PNPM 사용을 강제하는 스크립트 추가
